# uname -----------------------------------------------------------
OS=`uname -s`


# PATH ------------------------------------------------------------
case $OS in
	Darwin)
		export PATH=/opt/local/bin:/opt/local/sbin:$PATH
		;;
esac


# .bashrc ---------------------------------------------------------
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi
