<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>ASM</string>
	</array>
	<key>name</key>
	<string>Assembler</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.assembler</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.assembler</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(global)\s+([A-Za-z_]+)\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.assembler</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.assembler</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.definition.method.assembler</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(db|resd)\b</string>
			<key>name</key>
			<string>constant.language.c#</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*([a-zA-Z_]+[a-zA-Z_0-9]*)\s+\b(db|dd|dw|dq|dt|do)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.global.assembler</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.assembler</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>("|').*\1</string>
			<key>name</key>
			<string>string.quoted.assembler</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*([a-zA-Z_]+[a-zA-Z_0-9]*)\s+\b(resb|resw|resd|resq|rest|reso)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.global.uninitialised.assembler</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.assembler</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*([a-zA-Z_]+[a-zA-Z_0-9]*)\s+\b(equ)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.constant.assembler</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.assembler</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>[-+]?\b[0-9]+(\.[0-9]+)?\b|(?:\b((?:0x[a-f0-9]+)|(?:[a-f0-9]{2,}h)|[0-7]+(?:q|o)|(?:0|1){8,}+b|[0-9]+)|(?:\$0[a-f0-9]{2,}))\b</string>
			<key>name</key>
			<string>constant.numeric.assembler</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(salc|icebp|loadall|loadalld|sal|pop cs)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.undocumented</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(seg|wrt)\b</string>
			<key>name</key>
			<string>keyword.operator.assembler</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(aaa|aad|aam|aas|adc|add|and|call|cbw|clc|cld|cli|cmc|cmp|cmpsb|cmpsw|cwd|daa|das|dec|div|ec|hlt|idiv"imul|in|inc|int|into|iret|ja|jae|jb|jbe|jc|jcxz|je|jg|jge|jl|jle|jna|jnae|jnb|jnbe|jnc|jne|jng|jnge|jnl|jnle|jno|jnp|jns|jnz|jo|jp|jpe|jpo|js|jz|jmp|lahf|lds|lea|les|lock|lodsb|lodsw|loop|loope|loopne|loopnz|loopz|mov|movsb|movsw|mul|neg|nop|not|or|out|pop|popf|push|pushf|rcl|rcr|rep|repe|repne|repnz|repz|ret|retn|retf|rol|ror|sahf|sal|sar|bb|scasb|scasw|shl|shr|stc|std|sti|stosb|stosw|sub|test|wait|xchg|xlat|xor)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.8086</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bound|enter|ins|leave|outs|popa|pusha)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.80186</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(arpl|clts|lar|lgdt|lidt|lldt|lmsw|loadall|lsl|ltr|sgdt|sidt|sldt|smsw|str|verr|verw)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.80286</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bsf|bsr|bt|btc|btr|bts|cdq|cmpsd|cwde|insd|iretd|iretdf|iretf|jecxz|lfs|lgs|lss|lodsd|loopd|looped|loopned|loopnzd|loopzd|movsd|movsx|movzx|outsd|popad|popfd|pushad|pushd|pushfd|scasd|seta|setae|setb|setbe|setc|sete|setg|setge|setl|setle|setna|setnae|setnb|setnbe|setnc|setne|setng|setnge|setnl|setnle|setno|setnp|setns|setnz|seto|setp|setpe|setpo|sets|setz|shld|shrd|stosd)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.80386</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bswap|cmpxchg|invd|invlpg|wbinvd|xadd)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.80486</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cmpxchg8b|rdmsr|rdtsc|wrmsr)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.pentium</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\brdpmc\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.mmx</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cmova|cmovae|cmovb|cmovbe|cmovc|cmove|cmovg|cmovge|cmovl|cmovle|cmovna|cmovnae|cmovnb|cmovnbe|cmovnc|cmovne|cmovng|cmovnge|cmovnl|cmovnle|cmovno|cmovnp|cmovns|cmovnz|cmovo|cmovp|cmovpe|cmovpo|cmovs|cmovz|fcmov|fcmovb|fcmovbe|fcmove|fcmovnb|fcmovnbe|fcmovne|fcmovnu|fcmovu|fcomi|fcomip|fucomi|fucomip|sysenter|sysexit|rdpmc|ud2)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.pentium_pro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(syscall|sysret)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.amd_k6_2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(fxrstor|fxsave|maskmovq|movntps|movntq|prefetch0|prefetch1|prefetch2|prefetchnta|sfence)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.sse</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(clflush|lfence|maskmovdqu|mfence|movntdq|movnti|movntpd|pause)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.sse2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(fisttp|lddqu|monitor|mwait)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.sse3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(vmptrld|vmptrst|vmclear|vmread|vmwrite|vmcall|vmlaunch|vmresume|vmxoff|vmxon)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.intel_vt</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(clgi|skinit|stgi|vmload|vmmcall|vmrun|vmsave)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.amd_v</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cmpxchg16b|rdtscp)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.x86_64</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(lzcnt|popcnt)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.sse4a</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(f2xm1|fabs|fadd|faddp|fbld|fbstp|fchs|fclex|fcom|fcomp|fcompp|fdecstp|fdisi|fdiv|fdivp|fdivr|fdivrp|feni|ffree|fiadd|ficom|ficomp|fidiv|fidivr|fild|fimul|fincstp|finit|fist|fistp|fisub|fisubr|fld|fld1|fldcw|fldenv|fldenvw|fldl2e|fldl2t|fldlg2|fldln2|fldpi|fldz|fmul|fmulp|fnclex|fndisi|fneni|fninit|fnop|fnsave|fnsavew|fnstcw|fnstenv|fnstenvw|fnstsw|fpatan|fprem|fptan|frndint|frstor|frstorw|fsave|fsavew|fscale|fsqrt|fst|fstcw|fstenv|fstenvw|fstp|fstsw|fsub|fsubp|fsubr|fsubrp|ftst|fwait|fxam|fxch|fxtract|fyl2x|fyl2xp1)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.fpu.8087</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bfsetpm\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.fpu.80287</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(fcos|fldenvd|fnsaved|fnstenvd|fprem1|frstord|fsaved|fsin|fsincos|fstenvd|fucom|fucomp|fucompp)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.fpu.80387</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(emms|movd|movq|packssdw|packsswb|packuswb|paddb|paddd|paddsb|paddsw|paddusb|paddusw|paddw|pand|pandn|pcmpeqb|pcmpeqd|pcmpeqw|pcmpgtb|pcmpgtd|pcmpgtw|pmaddwd|pmulhw|pmullw|por|pslld|psllq|psllw|psrad|psraw|psrld|psrlq|psrlw|psubb|psubd|psubsb|psubsw|psubusb|psubusw|psubw|punpckhbw|punpckhdq|punpckhwd|punpcklbw|punpckldq|punpcklwd|pxor)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.simd.mmx</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(femms|pavgusb|pf2id|pfacc|pfadd|pfcmpeq|pfcmpge|pfcmpgt|pfmax|pfmin|pfmul|pfrcp|pfrcpit1|pfrcpit2|pfrsqit1|pfrsqrt|pfsub|pfsubr|pi2fd|pmulhrw|prefetch|prefetchw)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.simd.3dnow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(pf2iw|pfnacc|pfpnacc|pfrsqrtv|pfrcpv|pi2fw|pswapd)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.simd.3dnow_plus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(addps|addss|cmpps|cmpss|comiss|cvtpi2ps|cvtps2pi|cvtsi2ss|cvtss2si|cvttps2pi|cvttss2si|divps|divss|ldmxcsr|maxps|maxss|minps|minss|movaps|movhlps|movhps|movlhps|movlps|movmskps|movntps|movss|movups|mulps|mulss|rcpps|rcpss|rsqrtps|rsqrtss|shufps|sqrtps|sqrtss|stmxcsr|subps|subss|ucomiss|unpckhps|unpcklps)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.fpu.simd.sse</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(andnps|andps|orps|pavgb|pavgw|pextrw|pinsrw|pmaxsw|pmaxub|pminsw|pminub|pmovmskb|pmulhuw|psadbw|pshufw|xorps)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.simd.sse</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(addpd|addsd|andnpd|andpd|cmppd|cmpsd|comisd|cvtdq2pd|cvtdq2ps|cvtpd2dq|cvtpd2pi|cvtpd2ps|cvtpi2pd|cvtps2dq|cvtps2pd|cvtsd2si|cvtsd2ss|cvtsi2sd|cvtss2sd|cvttpd2dq|cvttpd2pi|cvtps2dq|cvttsd2si|divpd|divsd|maxpd|maxsd|minpd|minsd|movapd|movhpd|movlpd|movmskpd|movsd|movupd|mulpd|mulsd|orpd|shufpd|sqrtpd|sqrtsd|subpd|subsd|ucomisd|unpckhpd|unpcklpd|xorpd)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.fpu.simd.sse2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(movdq2q|movdqa|movdqu|movq2dq|paddq|psubq|pmuludq|pshufhw|pshuflw|pshufd|pslldq|psrldq|punpckhqdq|punpcklqdq)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.simd.sse2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(addsubpd|addsubps|haddpd|haddps|hsubpd|hsubps|movddup|movshdup|movsldup)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.fpu.simd.sse3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(psignw|psignd|psignb|pshufb|pmulhrsw|pmaddubsw|phsubw|phsubsw|phsubd|phaddw|phaddsw|phaddd|palignr|pabsw|pabsd|pabsb)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.simd.sse3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(mpsadbw|phminposuw|pmulld|pmuldq|dpps|dppd|blendps|blendpd|blendvps|blendvpd|pblendvb|pblendw|pminsb|pmaxsb|pminuw|pmaxuw|pminud|pmaxud|pminsd|pmaxsd|roundps|roundss|roundpd|roundsd|insertps|pinsrb|pinsrd/pinsrq|extractps|pextrb|pextrw|pextrd/pextrq|pmovsxbw|pmovzxbw|pmovsxbd|pmovzxbd|pmovsxbq|pmovzxbq|pmovsxwd|pmovzxwd|pmovsxwq|pmovzxwq|pmovsxdq|pmovzxdq|ptest|pcmpeqq|packusdw|movntdqa)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.simd.sse4_1</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(extrq|insertq|movntsd|movntss)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.simd.sse4_a</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(crc32|pcmpestri|pcmpestrm|pcmpistri|pcmpistrm|pcmpgtq)\b</string>
			<key>name</key>
			<string>keyword.opcodes.assembler.simd.sse4_2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(((a|b|c|d)(x|h|l))|(cs|ds|ss|es|sp|bp|si|di|flags|ip))\b</string>
			<key>name</key>
			<string>variable.registers.16bit</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((e(((a|b|c|d)x)|(cs|ds|ss|es|sp|bp|si|di|flags|ip)))|(fs|gs))\b</string>
			<key>name</key>
			<string>variable.registers.32bit</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((r(((a|b|c|d)x)|(cs|ds|ss|es|sp|bp|si|di|flags|ip)))|(r(8|9|1[0-5])))\b</string>
			<key>name</key>
			<string>variable.registers.64bit</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bmm[0-7]\b</string>
			<key>name</key>
			<string>variable.registers.mmx</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bxmm[0-7]\b</string>
			<key>name</key>
			<string>variable.registers.sse</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.assembler</string>
	<key>uuid</key>
	<string>33516C6F-F7AF-4C68-9DC9-BE401048A7DD</string>
</dict>
</plist>
